### ISSUE TITLE
Is Nodes ready for FreeCAD 1.0 Release ?

### ISSUE THREAD

**Issue by luzpaz** [j8sr0230/fc_nodes#136]
* https://github.com/FreeCAD/Addons/issues/13

**Comment by luzpaz** [comment]
Bump

**Comment by j8sr0230** [comment]
Not quite yet, trying to finish at the end of next week... Is there a deadline?

**Comment by luzpaz** [comment]
We're 1 [release blocker](https://github.com/FreeCAD/FreeCAD/issues?q=is%3Aopen+is%3Aissue+label%3ABlocker) away from releasing. It would be really nice if this wb was available for the influx of users who will be downloading FC and exploring it

**Comment by j8sr0230** [comment]
![image](https://github.com/user-attachments/assets/3dc64c89-28f9-4e6d-a9c5-6499206292a5)

Now I can confirm that Nodes installs with all dependencies, starts and works without any problems or warnings. Could not detect any system crash. The UI layout does not cause any issues either! 

Tested on this system:
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.47
  * lattice2 1.0.0
  * Nodes 0.1.36

Will there be a switch to PySide 6 in the near future?

**Comment by luzpaz** [comment]
Probably in the next development cycle (it's actually happening already) but will increase once 1.0 is out the door
