### ISSUE TITLE
Save FreeCAD nodes in this repository

### ISSUE THREAD

**Issue by FlachyJoe** [j8sr0230/fc_nodes#14]
Hi,
Your FreeCAD nodes are stored in your pyqt-node-editor fork, should be in this repository to let use them even with the pip available (original) pyqt-node-editor

**Comment by j8sr0230** [comment]
Thank you for your contribution. My pyqt-node-editor repository was actually kind of a playground to develop a pair of nodes relatively quickly. I will include all existing nodes from the examples folder in this repository shortly. All further development will take place here.
PS: I will take care of your pull requests as soon as possible. Great that the development is picking up speed :)
