### ISSUE TITLE
File->Exit close FreeCAD and cross button doesn't quit fc_nodes

### ISSUE THREAD

**Issue by FlachyJoe** [j8sr0230/fc_nodes#15]
- [x] When fc_nodes is launched under FreeCAD the file->exit menu cause FreeCAD to stop instead of closing only the fc_nodes window.
- [x] The cross button of the window only hide it: no question about saving the graphs.

**Comment by j8sr0230** [comment]
Fixed with [https://github.com/j8sr0230/fc_nodes/commit/8a28833d3e11e438c9ef425a51ff07da8839f7a7](https://github.com/j8sr0230/fc_nodes/commit/8a28833d3e11e438c9ef425a51ff07da8839f7a7).
