### ISSUE TITLE
Improve contribution process

### ISSUE THREAD

**Issue by FlachyJoe** [j8sr0230/fc_nodes#28]
@j8sr0230 
- Could you make PR even for your commits? Followers will then get notifications. To do this you have to commit your changes in another branch and PR from this one.
- Please consider setting up github code scanning https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository

**Comment by j8sr0230** [comment]
Corresponding GitHub action with a CodeQL code scanner has been set up.
