### ISSUE TITLE
Lack of visual feedback on nodes sockets

### ISSUE THREAD

**Issue by FlachyJoe** [j8sr0230/fc_nodes#48]
Depends on the zoom value it's not easy to put the wire on the circle.
A visual feedback (circle become bigger or lighter or other) should improve user's experience.

**Comment by j8sr0230** [comment]
@FlachyJoe Solved with commit [https://github.com/j8sr0230/fc_nodes/commit/177ba951547dd61a396d8720c5840580d83cf7a3](https://github.com/j8sr0230/fc_nodes/commit/177ba951547dd61a396d8720c5840580d83cf7a3)

![snapping](https://user-images.githubusercontent.com/39261150/193041024-e4eb48ad-bcf3-4c42-b833-5db08a7ab5f3.png)
720c5840580d83cf7a3)

**Comment by FlachyJoe** [comment]
Thank you !
