### ISSUE TITLE
Add pyqt-node-editor to allowed pip list in FreeCAD

### ISSUE THREAD

**Issue by luzpaz** [j8sr0230/fc_nodes#5]
Hey @chennes would if be OK if we added https://gitlab.com/pavel.krupala/pyqt-node-editor.git as an accepted 3rd party pip dependency so we can add this repo as an addon to FreeCAD-addons ?

**Comment by chennes** [comment]
I don't have any objection, feel free to add it to the allowed packages list.

**Comment by luzpaz** [comment]
chennes, I haven't looked at the code but will the addon manager be able to appropriately find and download pyqt-node-editor

**Comment by chennes** [comment]
As long as pip can find it: which typically means it has to be in pypi -- in this case, here: https://pypi.org/project/nodeeditor/

**Comment by luzpaz** [comment]
Dependencies have been added to upstream permission list via https://github.com/FreeCAD/FreeCAD-addons/pull/232
