### ISSUE TITLE
Adding a node doesn't trigger the onChange event

### ISSUE THREAD

**Issue by FlachyJoe** [j8sr0230/fc_nodes#51]
onChange event (shown by star in title bar) is triggered by node move and wire pulling but not by node drop nor context menu.

**Comment by j8sr0230** [comment]
@FlachyJoe Fixed with [https://github.com/j8sr0230/fc_nodes/commit/6e76b6e091e6c7a7450814e7fa192507e5939f0d](https://github.com/j8sr0230/fc_nodes/commit/6e76b6e091e6c7a7450814e7fa192507e5939f0d).
