### ISSUE TITLE
Turn this in to a workbench and add to the Addon Manager

### ISSUE THREAD

**Issue by luzpaz** [j8sr0230/fc_nodes#6]
#5  
https://github.com/FreeCAD/FreeCAD-addons/issues/231  
https://github.com/FreeCAD/FreeCAD-addons/pull/232  

Automate the rest of the [installation](https://github.com/j8sr0230/fc_nodes#installation) via the Addon Manager

**Comment by luzpaz** [comment]
@FlachyJoe what else needs to happen besides physically adding this to Addon Manager ?

**Comment by FlachyJoe** [comment]
You can already have it in your Addon Manager 
![Capture d’écran_2022-09-03_21-42-42](https://user-images.githubusercontent.com/10371513/188285641-83156e5f-d6ed-426c-acef-3c0830dbe19a.png)

and all users will see it soon: https://github.com/FreeCAD/FreeCAD-addons/issues/231

**Comment by luzpaz** [comment]
Awkward Arrays dependency has been approved as a 3rd party python library in the FreeCAD Addon Manager: https://github.com/FreeCAD/FreeCAD-addons/pull/241

**Comment by luzpaz** [comment]
Is there anything left for FC Nodes to install seamlessly from Addon Manager?

**Comment by j8sr0230** [comment]
No, everything there! The installation worked without problems:) Just tested it with the latest daily:

```
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.30716 (Git)
Build type: Release
Branch: master
Hash: cbd19631428f1d9eb4faae30220551608a648589
Python 3.10.6, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * CurvedShapes 1.0.3
  * Curves 0.5.0
  * DynamicData 2.46.0
  * fasteners 0.3.46
  * fc_nodes 0.1.0
  * lattice2 1.0.0
  * MyWorkbench
  * ThreadProfile 1.81.0
```
![fcn_install](https://user-images.githubusercontent.com/39261150/198581785-328e87bb-5921-4f91-a8dd-c33e3791d402.PNG)

**Comment by luzpaz** [comment]
Sweet! Lets update the README then ?
